try{
    let a = b;
}catch(e){
    console.log("error :"+e);
}