try{
    let a = b;
    //type of error
}catch(e){
    console.log("error :"+e);
}